### ISSUE TITLE
Vorschlagen neuer Orte

### ISSUE THREAD

**Issue by tmahlburg** [tmahlburg/jugendstadtplan#11]
Neue Orte sollten vorgeschlagen werden können, idealerweise über einen Link direkt in einem Pop-Up auf der Karte. Es sollte sich ein Kontaktformular öffnen, in dem die Ortsdaten (Längen- und Breitengrad) bereits übernommen wurden. Die übrigen Felder sollten vom Nutzer ausfüllbar sein und alle Elemente des Datenbankmodels enthalten.

**Comment by jonathom** [comment]
evtl von map verlinken und coords übernehmen

**Comment by tmahlburg** [comment]
Die Vorschlagsseite sollte erstmal ohne Funktion sein (keine Weiterleitung ans Admininterface. Nur die korrekte UI muss implementiert sein und die Verlinkung von einem Kartenpopup.

**Comment by tmahlburg** [comment]
Vorschlagsseite sollte auch vom empty state der Ortsliste erreichbar sein.
