### ISSUE TITLE
Orte gerne in Kategorien einordnen

### ISSUE THREAD

**Issue by JUSTHGW** [tmahlburg/jugendstadtplan#65]
Es wäre cool, wenn man die Orte in verschiedene Kategorien teilt (z.B. Beratung | Bildung | Freizeit | Kultur | Plätze | Politik | Freiwilligen Dienste | Schulen | FreeWIFI). Dies könnte man auf der Karte vielleicht auch anhand verschiedenfarbiger Markierungen verdeutlichen. (z.B. Beratung = blaue Markierung, Bildung = rote Markierung, ...)

**Comment by tmahlburg** [comment]
Das ist ja eigentlich schon die Idee von den Tags. Die Idee ist da ja dasselbe. Zwar kann das nicht durch die Farben gekennzeichnet werden, aber indem man die Tags ausschließt, kann man sich ja nur Orte anzeigen lassen, die bestimmten Tags entsprechen. Die meisten Orte sind ja auch nicht strikt einer Kategorie zuzuordnen, deswegen haben wir für die Tags als Alternative entschieden.

**Comment by tmahlburg** [comment]
Eine Idee wäre vielleicht, die Tags etwas sparsamer einzusetzen, damit sie besser zu benutzen sind. Also mit den Tags wirklich nur das wichtigste auszudrücken. Das ist dann aber natürlich etwas mehr Aufwand für euch als Administratoren, weil ihr da dann natürlich bei den Vorschlägen auch ein Auge drauf haben müsstet.

Eine andere Idee, um die Nutzbarkeit zu verbessern, kommt mir auch noch: Ich kann mal noch einen Button hinzufügen, mit dem man alle abwählen kann, damit man leichter nach einzelnen Tags filtern kann.

**Comment by JUSTHGW** [comment]
Hej, ja wir versuchen die Tags mal zu reduzieren. Die Idee mit dem "Abwähl-Button" ist schonmal sehr gut!

Wir hatten trotzdem überlegt, dass es cool wäre, wenn die Markierungen verschiedene Farben hätten. Ergibt das in deinen Augen Sinn? Dann ist das Ganze zu den Tags auch noch Visualisiert auf der Karte.

**Comment by tmahlburg** [comment]
Ja cool wäre es natürlich, aber ich kann es mir gerade noch nicht so richtig vorstellen, wonach soll sich die Farbe denn dann genau richten?

**Comment by JUSTHGW** [comment]
Vielleicht noch allgemeiner als die Tags. Also eine Einteilung wie Beratung | Bildung und Schulen | Freizeit und Sport | Kultur | Plätze| Politik. Für detaillierte Suchen (wie die einer kostenlosen Toilette, einer Tischtennisplatte oder eines WiFi-Spots) können dann die Tags dienen.

**Comment by tmahlburg** [comment]
Okay, also tatsächlich ein neues Eingabefeld. Dazu hab ich dann noch zwei Fragen und eine technische Info.

- Wonach soll man entscheiden, zu welcher Kategorie etwas gehört, wenn es mehreren zugehörig ist? Also am Beispiel JUST: Da würde ja von eurer Einteilung zum Beispiel "Bildung (und Schulen)", "Freizeit (und Sport)", "Kultur" und "Politik" passen. Wonach geht man dann?
- Welche Kategorien soll es genau geben? Da brauche ich eine Liste, die sich später auch nicht so ohne weiteres ändern lassen wird.

Zur Technik hab ich Kassi damals auch schon vorgewarnt, dass das Hinzufügen von neuen Eintragsmöglichkeiten (wie zum Beispiel eine Kategorieauswahl) nicht ganz unproblematisch ist. Von der Programmiererseite is es nicht so aufwendig, aber es ist nicht trivial, die Datenbank zu übernehmen. Das heißt, wenn es einen neuen Eintrag gibt, muss die Datenbank neu erstellt werden, also alle bisher eingetragenen Orte müssen per Hand neu eingetragen werden. Deswegen frag ich so viel nach und versuche herauszufinden, ob wir da noch eine andere Lösung finden. Also wenn euch das nicht stört, kann ich das natürlich trotzdem machen, ich will euch nur vorwarnen.

**Comment by JUSTHGW** [comment]
Hey Till, 

danke für deine schnellen Antworten und Problemlösungsvorschläge. :) 
Vielleicht können wir uns ja mal, nach deinen Prüfungen, auf ein Jitsi Meeting verabreden. 
Denn den Punkt mit der Datenbank check ich nicht so ganz und ich glaube dann werden auch unsere Anmerkungen vielleicht nochmal klarer. :) 
Kannst ja mal sagen, ab welchem Zeitpunkt das für dich wieder möglich wäre. 


Lieben Gruß 
Gesana 

#einmischen 
ein Projekt der gemeinsamen Jugendarbeit der evangelischen Altstadtgemeinden 
St. Jacobi, St. Marien und St. Nikolai 

An der Jacobikirche 6A 
17489 Greifswald 
Tel.: (03834) - 8832316 
oder mobil 0170 - 8832316 
E-Mail: zusammen@pek.de 
www.jugendimjacobiturm.de 


Von: "Till Mahlburg" <notifications@github.com> 
An: "tmahlburg/jugendstadtplan" <jugendstadtplan@noreply.github.com> 
CC: "Zusammen" <zusammen@pek.de>, "Author" <author@noreply.github.com> 
Gesendet: Dienstag, 2. Februar 2021 14:48:46 
Betreff: Re: [tmahlburg/jugendstadtplan] Orte gerne in Kategorien einordnen (#65) 





Okay, also tatsächlich ein neues Eingabefeld. Dazu hab ich dann noch zwei Fragen und eine technische Info. 

    * Wonach soll man entscheiden, zu welcher Kategorie etwas gehört, wenn es mehreren zugehörig ist? Also am Beispiel JUST: Da würde ja von eurer Einteilung zum Beispiel "Bildung (und Schulen)", "Freizeit (und Sport)", "Kultur" und "Politik" passen. Wonach geht man dann? 
    * Welche Kategorien soll es genau geben? Da brauche ich eine Liste, die sich später auch nicht so ohne weiteres ändern lassen wird. 


Zur Technik hab ich Kassi damals auch schon vorgewarnt, dass das Hinzufügen von neuen Eintragsmöglichkeiten (wie zum Beispiel eine Kategorieauswahl) nicht ganz unproblematisch ist. Von der Programmiererseite is es nicht so aufwendig, aber es ist nicht trivial, die Datenbank zu übernehmen. Das heißt, wenn es einen neuen Eintrag gibt, muss die Datenbank neu erstellt werden, also alle bisher eingetragenen Orte müssen per Hand neu eingetragen werden. Deswegen frag ich so viel nach und versuche herauszufinden, ob wir da noch eine andere Lösung finden. Also wenn euch das nicht stört, kann ich das natürlich trotzdem machen, ich will euch nur vorwarnen.

**Comment by tmahlburg** [comment]
Geplant sind jetzt nur zwei Kategorien: von Jugendlichen und für Jugendliche, die die Orte in zwei Farben unterscheiden.
