### ISSUE TITLE
Besser Listen: Die Seite wird nicht gefunden, wenn man jugendstadtplan googlet

### ISSUE THREAD

**Issue by JUSTHGW** [tmahlburg/jugendstadtplan#66]
Leider findet man die Seite noch nicht, wenn man sie googlet. Vielleicht gibts da ne möglichkeit, wie die einem schneller angezeigt wird.

**Comment by tmahlburg** [comment]
Da kann ich leider nicht so viel machen, weil dafür Googles Algorithmus zuständig ist. Da hilft vor allem, die Seite auf möglichst vielen anderen Seiten zu verlinken. Es dauert aber auch immer eine Weile, bis Google Internetseiten für ihre Suche indiziert.
